# Native Image with GraalVM

We are going to use https://www.graalvm.org[GraalVM], the polyglot embeddable virtual machine, to generate a Native image
of our Micronaut application.

Native images compiled with GraalVM ahead-of-time improve the startup time and reduce the memory footprint of JVM-based
applications.

Micronaut itself does not rely on reflection or dynamic classloading so works automatically with GraalVM native.

First, add Micronaut Graal's annotation processor that helps to handle generating the `reflection-config.json` metadata
that is automatically picked up by the `native-image` tool:

[source,groovy]
.build.gradle
----
dependencies {
...
..
.
include::{sourceDir}/../complete/build.gradle[tag=micronaut-graal]
}
----


> GraalVM Native Image allows you to ahead-of-time compile Java code to a standalone executable, called a native image.
This executable includes the application, the libraries, the JDK and does not run on the Java VM, but includes necessary
components like memory management and thread scheduling from a different virtual machine, called “Substrate VM”. Substrate
VM is the name for the runtime components (like the deoptimizer, garbage collector, thread scheduling etc.). The resulting
program has faster startup time and lower runtime memory overhead compared to a Java VM.

We need to add a dependency to `svm`:

[source,groovy]
.build.gradle
----
dependencies {
...
..
.
include::{sourceDir}/../complete/build.gradle[tag=svm]
}
----

You need to add a `native-image.properties` configuration file `src/main/resources/META-INF/native-image/application` to
simplify building the image.

[source,groovy]
.src/main/resources/META-INF/native-image/application/native-image.properties
----
include::{sourceDir}/../complete/src/main/resources/META-INF/native-image/application/native-image.properties[]
----

- The `-H:IncludeResources` argument allows you to tweak which static resources to include. You can use regular expressions.
- The `-H:Name` argument specifies the name of the native image that will be generated.
- The `-H:Class` argument specifies the entry point of your application (the class that defines a static void main method.


The easiest way to install GraalVM is to use https://sdkman.io[SDKMan.io].

[source,bash]
----
$ sdk list java
================================================================================
Available Java Versions
================================================================================
 Vendor        | Use | Version      | Dist    | Status     | Identifier
--------------------------------------------------------------------------------
....
 GraalVM       |     | 19.3.0.r11   | grl     | installed  | 19.3.0.r11-grl
               |     | 19.3.0.r8    | grl     | installed  | 19.3.0.r8-grl
               |     | 19.2.1       | grl     |            | 19.2.1-grl
               |     | 19.1.1       | grl     |            | 19.1.1-grl
               |     | 19.0.2       | grl     |            | 19.0.2-grl


# For Java 8
$ sdk install java 19.3.0.r8-grl

# For Java 11
$ sdk install java 19.3.0.r11-grl
----

You need to install the `native-image` component which is not installed by default.

[source,bash]
----
$ gu install native-image
----

To generate the native image you need to generate the FAT JAR first.

[source,bash]
----
$ ./gradlew assemble
----

Invoke `native-image`. It may take a minute to complete.

[source,bash]
----
$ which java
/Users/sdelamo/.sdkman/candidates/java/19.3.0.r8-grl/bin/java

$ native-image --no-server -cp build/libs/complete-0.1-all.jar
[micronautguide:39362]    classlist:   3,884.97 ms
[micronautguide:39362]        (cap):   5,919.80 ms
[micronautguide:39362]        setup:   7,222.88 ms
[micronautguide:39362]   (typeflow):  14,037.78 ms
[micronautguide:39362]    (objects):  17,689.40 ms
[micronautguide:39362]   (features):   1,751.37 ms
[micronautguide:39362]     analysis:  35,421.99 ms
[micronautguide:39362]     (clinit):     978.01 ms
[micronautguide:39362]     universe:   2,114.65 ms
[micronautguide:39362]      (parse):   2,327.75 ms
[micronautguide:39362]     (inline):   2,153.46 ms
[micronautguide:39362]    (compile):  13,066.94 ms
[micronautguide:39362]      compile:  19,714.97 ms
[micronautguide:39362]        image:   3,509.84 ms
[micronautguide:39362]        write:   1,114.96 ms
[micronautguide:39362]      [total]:  73,294.82 ms
----

`--no-server` options tells to not use server-based image building.

You can invoke the generated native image `micronautguide`. Startup will be really fast.

[source, bash]
----
 $ ./micronautguide
07:42:20.792 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 21ms. Server Running: http://localhost:8080
----

Alternatively, you can use `Dockerfile`  to construct the native image and a script `docker-build.sh` to run it:

[source,bash]
.Dockerfile
----
FROM oracle/graalvm-ce:19.3.0-java8 as graalvm
#FROM oracle/graalvm-ce:19.3.0-java11 as graalvm # For JDK 11
COPY . /home/app/micronautguide
WORKDIR /home/app/micronautguide
RUN gu install native-image
RUN yum install -y libstdc++-static
RUN native-image --no-server --static -cp build/libs/complete-*-all.jar

FROM frolvlad/alpine-glibc
EXPOSE 8080
COPY --from=graalvm /home/app/micronautguide/micronautguide /app/micronautguide
ENTRYPOINT ["/app/micronautguide"]
----

[source,bash]
.docker-build.sh
----
include::{sourceDir}/../complete/docker-build.sh[]
----

[source, bash]
----
$ ./gradlew assemble

$ ./docker-build.sh
Sending build context to Docker daemon  64.67MB
Step 1/10 : FROM oracle/graalvm-ce:19.3.0-java8 as graalvm
 ---> d625000893c9
Step 2/10 : COPY . /home/app/micronautguide
 ---> 4c0daf50c6f3
Step 3/10 : WORKDIR /home/app/micronautguide
 ---> Running in e07cf22b668a
Removing intermediate container e07cf22b668a
 ---> d3699ea8e284
Step 4/10 : RUN gu install native-image
 ---> Running in 71edf17b9a11
Downloading: Component catalog from www.graalvm.org
Processing Component: Native Image
Downloading: Component native-image: Native Image  from github.com
Installing new component: Native Image (org.graalvm.native-image, version 19.3.0)
Refreshed alternative links in /usr/bin/
Removing intermediate container 71edf17b9a11
 ---> ee26c71bbd1e
Step 5/10 : RUN yum install -y libstdc++-static
 ---> Running in 0f48db1f6f17
Removing intermediate container 0f48db1f6f17
 ---> c943e492cfda
Step 6/10 : RUN native-image --no-server --static -cp build/libs/complete-*-all.jar
 ---> Running in d2cd451f33be
[micronautguide:28]    classlist:   8,773.36 ms
[micronautguide:28]        (cap):   1,044.04 ms
[micronautguide:28]        setup:   2,748.03 ms
[micronautguide:28]   (typeflow):  20,611.56 ms
[micronautguide:28]    (objects):  20,377.15 ms
[micronautguide:28]   (features):   2,168.30 ms
[micronautguide:28]     analysis:  45,559.16 ms
[micronautguide:28]     (clinit):   1,141.31 ms
[micronautguide:28]     universe:   2,719.10 ms
[micronautguide:28]      (parse):   2,808.15 ms
[micronautguide:28]     (inline):   3,094.66 ms
[micronautguide:28]    (compile):  25,648.31 ms
[micronautguide:28]      compile:  34,018.50 ms
[micronautguide:28]        image:   3,811.46 ms
[micronautguide:28]        write:     643.59 ms
[micronautguide:28]      [total]:  99,095.08 ms
Removing intermediate container d2cd451f33be
 ---> 429a467e2fdd
Step 7/10 : FROM frolvlad/alpine-glibc
 ---> 38dd85a430e8
Step 8/10 : EXPOSE 8080
 ---> Using cache
 ---> 643f9d29e3f8
Step 9/10 : COPY --from=graalvm /home/app/micronautguide/micronautguide /app/micronautguide
 ---> 0d41749e3ceb
Step 10/10 : ENTRYPOINT ["/app/micronautguide"]
 ---> Running in 31b4c6c21e68
Removing intermediate container 31b4c6c21e68
 ---> 3ff1de337ef4
Successfully built 3ff1de337ef4
Successfully tagged micronautguide:latest


To run the docker container execute:
    $ docker run -p 8080:8080 micronautguide
----

You can use docker to run the image with the app's native-image:

[source, bash]
----
 docker run -p 8080:8080 micronautguide
06:58:26.977 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 27ms. Server Running: http://f8143044b1ee:8080
----
